### ISSUE TITLE
Issue running the bot

### ISSUE THREAD

**Issue by kroil** [PiotrRut/elonmusk-twitter-notifier#3]
Hi there,

first off, thanks for sharing the code. I am just not able to start it. I am getting the following output:

```
Traceback (most recent call last):
  File "/Users/fs/PycharmProjects/elon-musk-bot/src/scanner.py", line 3, in <module>
    from tweets import tweet_engine
  File "/Users/fs/PycharmProjects/elon-musk-bot/src/tweets.py", line 20, in <module>
    detector.loadModel()
  File "/Users/fs/PycharmProjects/elon-musk-bot/venv/lib/python3.8/site-packages/imageai/Detection/Custom/__init__.py", line 666, in loadModel
    self.__model.load_weights(self.__model_path)
  File "/Users/fs/PycharmProjects/elon-musk-bot/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 2234, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/Users/fs/PycharmProjects/elon-musk-bot/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 710, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/Users/fs/PycharmProjects/elon-musk-bot/venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/fs/PycharmProjects/elon-musk-bot/venv/lib/python3.8/site-packages/tensorflow/python/keras/backend.py", line 3706, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/Users/fs/PycharmProjects/elon-musk-bot/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 888, in assign
    raise ValueError(
ValueError: Cannot assign to variable last1/kernel:0 due to variable shape (1, 1, 1024, 21) and value shape (27, 1024, 1, 1) are incompatible
```

Any idea how I can solve that issue? Thanks a lot!

**Comment by kroil** [comment]
Oh it appears that removing keywords in `detection_config` breaks the code.

**Comment by kroil** [comment]
How would I go if Id like to update / change the labels in `detection_config`? Is that complex or easy to do? Thanks for your help.
